apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.seafile.configs.seafileDataVolume.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.seafile.configs.seafileDataVolume.storage }}
  volumeName: seafile-data