apiVersion: v1
kind: Service
metadata:
  name: seafile
spec:
  selector:
    app: seafile
  type: {{ .Values.seafile.service.type }}
  {{- if .Values.seafile.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.seafile.service.loadBalancerIP }}
  {{- end }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
