apiVersion: v1
kind: PersistentVolume
metadata:
  name: seafile-data2
spec:
  capacity:
    storage: {{ .Values.seafile.configs.seafileDataVolume.storage }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.seafile.configs.seafileDataVolume.storageClassName }}
  {{ if .Values.seafile.configs.seafileDataVolume.nfs.enabled }}
  nfs:
    server: {{ .Values.seafile.configs.seafileDataVolume.nfs.serverIP }}
    path: {{ .Values.seafile.configs.seafileDataVolume.nfs.serverPath }}
  mountOptions:
    - nfsvers=4.1
  {{ else }}
  hostPath:
    path: {{ .Values.seafile.configs.seafileDataVolume.hostPath }}
  {{ end }}