seafile:
  initMode: true
  configs: {} # seafile container configurations, object
  env: {} # environment variables for seafile service, object
  secretsMap: {} # seafile services secrets env, object
  
  # extra infomations object(frontend, backend)
  extraResources: {}
  extraEnv: []
  extraVolumes: []

  # Default
  presetEnv:
    # for Seafile server
    - name: TIME_ZONE
      value: "UTC"
    - name: SEAFILE_LOG_TO_STDOUT
      value: "true"
    - name: SITE_ROOT
      value: "/"
    - name: SEAFILE_SERVER_HOSTNAME
    - name: SEAFILE_SERVER_PROTOCOL
      value: "https"

    # for database
    - name: SEAFILE_MYSQL_DB_HOST
    - name: SEAFILE_MYSQL_DB_PORT
      value: "3306"
    - name: SEAFILE_MYSQL_DB_USER
      value: "seafile"
    - name: SEAFILE_MYSQL_DB_CCNET_DB_NAME
      value: "ccnet_db"
    - name: SEAFILE_MYSQL_DB_SEAFILE_DB_NAME
      value: "seafile_db"
    - name: SEAFILE_MYSQL_DB_SEAHUB_DB_NAME
      value: "seahub_db"

    # for cache
    - name: CACHE_PROVIDER
      value: "redis"

    ## for redis
    - name: REDIS_HOST
      allowEmpty: true
    - name: REDIS_PORT
      value: "6379"

    ## for memcached
    - name: MEMCACHED_HOST
      allowEmpty: true
    - name: MEMCACHED_PORT
      value: "11211"

    # for s3
    - name: SEAF_SERVER_STORAGE_TYPE
      allowEmpty: true
    - name: S3_COMMIT_BUCKET
      allowEmpty: true
    - name: S3_FS_BUCKET
      allowEmpty: true
    - name: S3_BLOCK_BUCKET
      allowEmpty: true
    - name: S3_KEY_ID
      allowEmpty: true
    - name: S3_USE_V4_SIGNATURE
      value: "true"
    - name: S3_AWS_REGION
      value: "us-east-1"
    - name: S3_HOST
      allowEmpty: true
    - name: S3_USE_HTTPS
      value: "true"
    - name: S3_PATH_STYLE_REQUEST
      value: "false"

    # for notification
    - name: NOTIFICATION_SERVER_URL
      allowEmpty: true

    # for seadoc
    - name: ENABLE_SEADOC
      value: "false"
    - name: SEADOC_SERVER_URL
      allowEmpty: true

    # initialization

    ## for Seafile admin
    - name: INIT_SEAFILE_ADMIN_EMAIL
      initValue: true

  presetSecretsMap:
    - name: INIT_SEAFILE_MYSQL_ROOT_PASSWORD # Env's name
      secret: seafile-secret
      key: INIT_SEAFILE_MYSQL_ROOT_PASSWORD
    - name: JWT_PRIVATE_KEY
      secret: seafile-secret
      key: JWT_PRIVATE_KEY
    - name: SEAFILE_MYSQL_DB_PASSWORD
      secret: seafile-secret
      key: SEAFILE_MYSQL_DB_PASSWORD
    - name: INIT_SEAFILE_ADMIN_PASSWORD
      secret: seafile-secret
      key: INIT_SEAFILE_ADMIN_PASSWORD
    - name: S3_SECRET_KEY
      secret: seafile-secret
      key: S3_SECRET_KEY
    - name: S3_SSE_C_KEY
      secret: seafile-secret
      key: S3_SSE_C_KEY
    - name: REDIS_PASSWORD
      secret: seafile-secret
      key: REDIS_PASSWORD
    